version: '3.8'
services:
  app:
    container_name: scraping-github
    image: rickes/scraping-spring-postgres:1.0.0
    ports:
      - "8080:8080"
    depends_on:
      - postgresqldb
  postgresqldb:
    image: postgres
    container_name: postgresqldb
    ports:
      - "5432:5432"
    expose:
      - 5432
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=postgres
      - POSTGRES_DB=scrapingdb